// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdmWuWYZz3qIeeT8ny9H5aDJiiCwlY_Dw',
    appId: '1:859453780170:web:f722c0ca5c3d410e1d8433',
    messagingSenderId: '859453780170',
    projectId: 'boom-boom-ad8ec',
    authDomain: 'boom-boom-ad8ec.firebaseapp.com',
    storageBucket: 'boom-boom-ad8ec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5eUNYtQYXFz2JA_e0D7I2eEFun2Mq49Q',
    appId: '1:859453780170:android:21de6899b0e31e1f1d8433',
    messagingSenderId: '859453780170',
    projectId: 'boom-boom-ad8ec',
    storageBucket: 'boom-boom-ad8ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWOA70nHHGmVjiyZJXdXlM1BVbeEPBmKE',
    appId: '1:859453780170:ios:63dbaf96e246d4491d8433',
    messagingSenderId: '859453780170',
    projectId: 'boom-boom-ad8ec',
    storageBucket: 'boom-boom-ad8ec.appspot.com',
    iosClientId:
        '859453780170-51c3imulfmvtvspqksd84p5grntbhu8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWOA70nHHGmVjiyZJXdXlM1BVbeEPBmKE',
    appId: '1:859453780170:ios:63dbaf96e246d4491d8433',
    messagingSenderId: '859453780170',
    projectId: 'boom-boom-ad8ec',
    storageBucket: 'boom-boom-ad8ec.appspot.com',
    iosClientId:
        '859453780170-51c3imulfmvtvspqksd84p5grntbhu8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
